In [1]:
import numpy as np
import pandas as pd

In [2]:
import os

In [3]:
df = pd.read_csv('/Users/hunjunsin/Desktop/python/Kaggle/adclickpredict/ad_click_dataset.csv')
df.head()

id full_name   age      gender device_type ad_position browsing_history  \
0   670   User670  22.0         NaN     Desktop         Top         Shopping   
1  3044  User3044   NaN        Male     Desktop         Top              NaN   
2  5912  User5912  41.0  Non-Binary         NaN        Side        Education   
3  5418  User5418  34.0        Male         NaN         NaN    Entertainment   
4  9452  User9452  39.0  Non-Binary         NaN         NaN     Social Media   

  time_of_day  click  
0   Afternoon      1  
1         NaN      1  
2       Night      1  
3     Evening      1  
4     Morning      0

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   id                10000 non-null  int64  
 1   full_name         10000 non-null  object 
 2   age               5234 non-null   float64
 3   gender            5307 non-null   object 
 4   device_type       8000 non-null   object 
 5   ad_position       8000 non-null   object 
 6   browsing_history  5218 non-null   object 
 7   time_of_day       8000 non-null   object 
 8   click             10000 non-null  int64  
dtypes: float64(1), int64(2), object(6)
memory usage: 703.3+ KB


In [5]:
import matplotlib.pyplot as plt

In [6]:
gender = df['gender'].value_counts()

In [7]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier, AdaBoostClassifier, ExtraTreesClassifier
from xgboost import XGBClassifier
from catboost import CatBoostClassifier
from lightgbm import LGBMClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.linear_model import LogisticRegression

In [9]:
models = {
    'Random Forest': RandomForestClassifier(random_state=10),
    'Gradient Boosting': GradientBoostingClassifier(random_state=10),
    'Ada Boost': AdaBoostClassifier(random_state=10),
    'Extra Trees': ExtraTreesClassifier(random_state=10),
    'XGBoost': XGBClassifier(random_state=10),
    'Cat Boost': CatBoostClassifier(random_state=10, verbose=False),
    'Light GBM': LGBMClassifier(random_state=10, verbose=-1),
    'Decision Tree': DecisionTreeClassifier(random_state=10),
    'Logistic Regression': LogisticRegression(random_state=10)
}

In [10]:
df = df.drop(['full_name'], axis = 1)

In [11]:
df.isnull().sum()

id                     0
age                 4766
gender              4693
device_type         2000
ad_position         2000
browsing_history    4782
time_of_day         2000
click                  0
dtype: int64

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   id                10000 non-null  int64  
 1   age               5234 non-null   float64
 2   gender            5307 non-null   object 
 3   device_type       8000 non-null   object 
 4   ad_position       8000 non-null   object 
 5   browsing_history  5218 non-null   object 
 6   time_of_day       8000 non-null   object 
 7   click             10000 non-null  int64  
dtypes: float64(1), int64(2), object(5)
memory usage: 625.1+ KB


In [15]:
df['age'] = df['age'].fillna(df['age'].mean())
df['gender'] = df['gender'].fillna("Unknown")
df['device_type'] = df['device_type'].fillna("Unknown")
df['ad_position'] = df['ad_position'].fillna("Unknown")
df['browsing_history'] = df['browsing_history'].fillna("Unknown")
df['time_of_day'] = df['time_of_day'].fillna("Unknown")

In [16]:
df.isnull().sum()

id                  0
age                 0
gender              0
device_type         0
ad_position         0
browsing_history    0
time_of_day         0
click               0
dtype: int64

In [17]:
le = LabelEncoder()

In [19]:
df['gender'] = le.fit_transform(df['gender'])
df['device_type'] = le.fit_transform(df['device_type'])
df['ad_position'] = le.fit_transform(df['ad_position'])
df['browsing_history'] = le.fit_transform(df['browsing_history'])
df['time_of_day'] = le.fit_transform(df['time_of_day'])

In [21]:
df['gender'].value_counts

<bound method IndexOpsMixin.value_counts of 0       3
1       1
2       2
3       1
4       2
       ..
9995    3
9996    0
9997    1
9998    3
9999    1
Name: gender, Length: 10000, dtype: int64>

In [22]:
X = df.drop('click' ,axis=1)
y = df['click']

In [25]:
X.head()

id        age  gender  device_type  ad_position  browsing_history  \
0   670  22.000000       3            0            2                 3   
1  3044  40.197363       1            0            2                 5   
2  5912  41.000000       2            3            1                 0   
3  5418  34.000000       1            3            3                 1   
4  9452  39.000000       2            3            3                 4   

   time_of_day  
0            0  
1            4  
2            3  
3            1  
4            2

In [26]:
y.head()

0    1
1    1
2    1
3    1
4    0
Name: click, dtype: int64

In [27]:
X.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 7 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   id                10000 non-null  int64  
 1   age               10000 non-null  float64
 2   gender            10000 non-null  int64  
 3   device_type       10000 non-null  int64  
 4   ad_position       10000 non-null  int64  
 5   browsing_history  10000 non-null  int64  
 6   time_of_day       10000 non-null  int64  
dtypes: float64(1), int64(6)
memory usage: 547.0 KB


In [28]:
y.info()

<class 'pandas.core.series.Series'>
RangeIndex: 10000 entries, 0 to 9999
Series name: click
Non-Null Count  Dtype
--------------  -----
10000 non-null  int64
dtypes: int64(1)
memory usage: 78.3 KB


In [29]:
X.shape

(10000, 7)

In [30]:
y.shape

(10000,)

In [32]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.1, random_state = 42)

In [33]:
X_train.shape

(9000, 7)

In [34]:
X_test.shape

(1000, 7)

In [37]:
for name, model in models.items():
    print(name)
    model.fit(X_train, y_train)
    y_pred = model.predict(X_test)
    accuracy = accuracy_score(y_test, y_pred)
    
    print("Accuracy : ", accuracy)
    print("Confusion_matrix :")
    print(confusion_matrix(y_test, y_pred))
    print("Classificaiton Report")
    print(classification_report(y_test, y_pred))
    
    print("-"*50)

Random Forest
Accuracy :  0.796
Confusion_matrix :
[[201 163]
 [ 41 595]]
Classificaiton Report
              precision    recall  f1-score   support

           0       0.83      0.55      0.66       364
           1       0.78      0.94      0.85       636

    accuracy                           0.80      1000
   macro avg       0.81      0.74      0.76      1000
weighted avg       0.80      0.80      0.78      1000

--------------------------------------------------
Gradient Boosting
Accuracy :  0.693
Confusion_matrix :
[[ 59 305]
 [  2 634]]
Classificaiton Report
              precision    recall  f1-score   support

           0       0.97      0.16      0.28       364
           1       0.68      1.00      0.81       636

    accuracy                           0.69      1000
   macro avg       0.82      0.58      0.54      1000
weighted avg       0.78      0.69      0.61      1000

--------------------------------------------------
Ada Boost
Accuracy :  0.653
Confusion_matrix :
[

/opt/anaconda3/lib/python3.12/site-packages/sklearn/ensemble/_weight_boosting.py:519: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(


Accuracy :  0.783
Confusion_matrix :
[[210 154]
 [ 63 573]]
Classificaiton Report
              precision    recall  f1-score   support

           0       0.77      0.58      0.66       364
           1       0.79      0.90      0.84       636

    accuracy                           0.78      1000
   macro avg       0.78      0.74      0.75      1000
weighted avg       0.78      0.78      0.77      1000

--------------------------------------------------
XGBoost
Accuracy :  0.838
Confusion_matrix :
[[228 136]
 [ 26 610]]
Classificaiton Report
              precision    recall  f1-score   support

           0       0.90      0.63      0.74       364
           1       0.82      0.96      0.88       636

    accuracy                           0.84      1000
   macro avg       0.86      0.79      0.81      1000
weighted avg       0.85      0.84      0.83      1000

--------------------------------------------------
Cat Boost
Accuracy :  0.778
Confusion_matrix :
[[152 212]
 [ 10 626]]
Cl

/opt/anaconda3/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/opt/anaconda3/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/opt/anaconda3/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels

In [46]:
model_DTC= DecisionTreeClassifier(random_state = 10)
model_DTC.fit(X_train, y_train)
y_pred = model_DTC.predict(X_test)

In [51]:
sum(np.isclose(y_pred, y_test))

851

In [53]:
from sklearn.model_selection import GridSearchCV

param_grids = {
    'Decision Tree': {
       'max_depth': [3, 5, 10, 15],
       'min_samples_split': [2, 5, 10],
       'min_samples_leaf': [1, 5, 10]
    },
    'XGBoost': {
       'max_depth': [3, 5, 10],
        'learning_rate': [0.1, 0.5, 1],
        'n_estimators': [50, 100, 200]
    },
    'Random Forest': {
        'n_estimators': [50, 100, 200],
       'max_depth': [3, 5, 10],
       'min_samples_split': [2, 5, 10]
    }
}

In [56]:
for name, model in models.items():
    if name not in param_grids:
        continue
    
    grid_search = GridSearchCV(model, param_grids[name], cv=5, scoring='accuracy', verbose =1)
    grid_search.fit(X_train, y_train)
    y_pred = grid_search.predict(X_test)
    
    print(f"Best Parameters for : {name}: {grid_search.best_params_}")
    print(f"Best score for : {name}: {grid_search.best_score_}")
    
    accuracy = accuracy_score(y_test, y_pred)
    print("Accuracy:", accuracy)
    print("Classification_Report: ")
    print(classification_report(y_test, y_pred))
    print("Confusion Matrix: ")
    print(confusion_matrix(y_test, y_pred))
    print("*"*30)

Fitting 5 folds for each of 27 candidates, totalling 135 fits
Best Parameters for : Random Forest: {'max_depth': 10, 'min_samples_split': 2, 'n_estimators': 50}
Best score for : Random Forest: 0.7060000000000001
Accuracy: 0.691
Classification_Report: 
              precision    recall  f1-score   support

           0       0.97      0.16      0.27       364
           1       0.67      1.00      0.80       636

    accuracy                           0.69      1000
   macro avg       0.82      0.58      0.54      1000
weighted avg       0.78      0.69      0.61      1000

Confusion Matrix: 
[[ 57 307]
 [  2 634]]
******************************
Fitting 5 folds for each of 27 candidates, totalling 135 fits
Best Parameters for : XGBoost: {'learning_rate': 0.5, 'max_depth': 10, 'n_estimators': 200}
Best score for : XGBoost: 0.8523333333333334
Accuracy: 0.871
Classification_Report: 
              precision    recall  f1-score   support

           0       0.89      0.73      0.81       364
